const statesNames = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming"
];
const stateNamesAb = [
  ["AL", "ALABAMA"],
  ["AK", "ALASKA"],
  ["AZ", "ARIZONA"],
  ["AR", "ARKANSAS"],
  ["CA", "CALIFORNIA"],
  ["CO", "COLORADO"],
  ["CT", "CONNECTICUT"],
  ["DE", "DELAWARE"],
  ["DC", "DISTRICT OF COLUMBIA"],
  ["FL", "FLORIDA"],
  ["GA", "GEORGIA"],
  ["GU", "GUAM GU"],
  ["HI", "HAWAII"],
  ["ID", "IDAHO"],
  ["IL", "ILLINOIS"],
  ["IN", "INDIANA"],
  ["IA", "IOWA"],
  ["KS", "KANSAS"],
  ["KY", "KENTUCKY"],
  ["LA", "LOUISIANA"],
  ["ME", "MAINE"],
  ["MH", "MARSHALL ISLANDS"],
  ["MD", "MARYLAND"],
  ["MA", "MASSACHUSETTS"],
  ["MI", "MICHIGAN"],
  ["MN", "MINNESOTA"],
  ["MS", "MISSISSIPPI"],
  ["MO", "MISSOURI"],
  ["MT", "MONTANA"],
  ["NE", "NEBRASKA"],
  ["NV", "NEVADA"],
  ["NH", "NEW HAMPSHIRE"],
  ["NJ", "NEW JERSEY"],
  ["NM", "NEW MEXICO"],
  ["NY", "NEW YORK"],
  ["NC", "NORTH CAROLINA"],
  ["ND", "NORTH DAKOTA"],
  ["OH", "OHIO"],
  ["OK", "OKLAHOMA"],
  ["OR", "OREGON"],
  ["PA", "PENNSYLVANIA"],
  ["RI", "RHODE ISLAND"],
  ["SC", "SOUTH CAROLINA"],
  ["SD", "SOUTH DAKOTA"],
  ["TN", "TENNESSEE"],
  ["TX", "TEXAS"],
  ["UT", "UTAH"],
  ["VT", "VERMONT"],
  ["VA", "VIRGINIA"],
  ["WA", "WASHINGTON"],
  ["WV", "WEST VIRGINIA"],
  ["WI", "WISCONSIN"],
  ["WY", "WYOMING"]
];
export default stateNamesAb;
