// Notifications
export const SHOW_INFO_MESSAGE = "SHOW_INFO_MESSAGE";
export const SHOW_SUCCESS_MESSAGE = "SHOW_SUCCESS_MESSAGE";
export const SHOW_wARNING_MESSAGE = "SHOW_wARNING_MESSAGE";
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE";

export const HIDE_INFO_MESSAGE = "HIDE_INFO_MESSAGE";
export const HIDE_SUCCESS_MESSAGE = "HIDE_SUCCESS_MESSAGE";
export const HIDE_wARNING_MESSAGE = "HIDE_wARNING_MESSAGE";
export const HIDE_ERROR_MESSAGE = "HIDE_ERROR_MESSAGE";

// ContactDetailCard
export const TOGGLE_RIGHT_COLUMN = "TOGGLE_RIGHT_COLUMN";
export const SET_CONTACT_DETAIL_CARD_STATE = "SET_CONTACT_DETAIL_CARD_STATE";

// ContactDetailCard
export const TOGGLE_MAP_GRID_ACTIVATED = "TOGGLE_MAP_GRID_ACTIVATED";
export const SET_MAP_GRID_CARD_STATE = "SET_MAP_GRID_CARD_STATE";
