import React, { useContext, useEffect } from "react";
import TextField from "@material-ui/core/TextField";
import Autocomplete from "@material-ui/lab/Autocomplete";
import { NavigationContext } from "../NavigationContext";

const operatorList = [
  "1849 ENERGY PARTNERS OPRTNG LLC",
  "4SIGHT OPERATING COMPANY",
  "ABRAXAS PETROLEUM",
  "ACADIA OIL",
  "ACOCK/ANAQUA OPERATING COMPANY",
  "ADAMS AFFILIATES",
  "AETHON ENERGY OPERATING",
  "AGHORN OPERATING",
  "AMERADA HESS",
  "AMERICAN PETROFINA CO OF TEX",
  "AMERICO ENERGY RESOURCES",
  "AMOCO PRODUCTION COMPANY",
  "AMPLIFY ENERGY OPERATING",
  "ANADARKO PETROLEUM",
  "ANDERSON JAMES K",
  "APACHE",
  "APPROACH OPERATING",
  "APV MCCAMEY",
  "ARCADIA OPERATING",
  "ARCH OIL AND GAS COMPANY",
  "ARCO OIL AND GAS COMPANY",
  "ARMOR PETROLEUM",
  "ARROWHEAD PRODUCTION",
  "ASPEN OPERATING COMPANY",
  "ATLANTIC RICHFIELD COMPANY",
  "ATLAS OPERATING",
  "ATMOS ENERGY CORP MIDTEX DIV",
  "AURORA RESOURCES",
  "AVALON TX OPERATING LLC",
  "AZTECA PETROLEUM",
  "B AND B OIL",
  "BAKER OPERATING",
  "BALLARD EXPLORATION COMPANYINC",
  "BANNER OIL AND GAS",
  "BAR L PRODUCERS",
  "BASA RESOURCES",
  "BASTROP OIL AND GAS",
  "BAYLOR OPERATING",
  "BCEMACH II LLC",
  "BEDROCK PRODUCTION LLC",
  "BERRY OIL COMP",
  "BETTIS BOYLE AND STOVALL",
  "BHP BILLITON PETROLEUM",
  "BIRCH OPERATIONS",
  "BLACK BAYOU OPERATING",
  "BLACKBEARD OPERATING",
  "BLACKBRUSH O AND G",
  "BLS PRODUCTION",
  "BLUESTONE NATURAL RES II",
  "BOAZ ENERGY II OPERATING",
  "BORDERLINE OPERATING",
  "BP AMERICA PRODUCTION COMPANY",
  "BPX OPERATING COMPANY",
  "BRADLEY OPERATING COMPANY",
  "BRAKA OPERATING",
  "BRECK OPERATING",
  "BREITBURN OPERATING",
  "BRG LONE STAR",
  "BRIDWELL OIL COMPANY",
  "BROWN GEO R LPTHE",
  "BTA OIL PRODUCERS",
  "BUFFCO PRODUCTION",
  "BURK ROYALTY",
  "BURK ROYALTY COMPANY",
  "BURLINGTON RESOURCES OIL AND GAS COMPANY",
  "BXP OPERATING",
  "C AND E OPERATING",
  "CADDO ENERGY",
  "CALLON PETROLEUM COMPANY",
  "CALTEX ENERGY COMPANY",
  "CAMBRIAN MANAGEMENT",
  "CARRIZO OIL AND GAS",
  "CBP OPERATING",
  "CCI EAST TEXAS UPSTREAM",
  "CCI GULF COAST UPSTREAM",
  "CENTENNIAL RESOURCE PRODUCTION",
  "CENTURY PETROLEUM",
  "CHAMPION LONE STAR OPERATINGLLC",
  "CHAMPLIN PETROLEUM COMPANY",
  "CHARRO OPERATING",
  "CHESAPEAKE OPERATING",
  "CHEVRON",
  "CHOLLA PETROLEUM",
  "CIMAREX ENERGY COMPANY",
  "CITATION OIL AND GAS",
  "CITIES SERVICE OIL COMPANY",
  "CLARK OIL COMPANY",
  "CLAYTON WILLIAMS ENERGY",
  "CLEAR FORK INCORPORATED",
  "CLEARLY PETROLEUM",
  "CML EXPLORATION",
  "COASTAL OIL AND GAS",
  "COBRA OIL AND GAS",
  "COG OPERATING",
  "COLUMBUS ENERGY",
  "COMPASS ENERGY OPERATING",
  "COMSTOCK OIL AND GAS",
  "COMSTOCK OIL AND GASLA",
  "CONOCO",
  "CONOCOPHILLIPS CANADA RESOURCES",
  "CONTINENTAL OIL COMPANY",
  "COOPER OIL AND GAS",
  "CORPUS CHRISTI OIL AND GAS COMPANY",
  "COTTONWOOD PETROLEUM COMPANY",
  "COURSON OIL AND GAS",
  "COX JOHNLLC",
  "CRAIG BOB",
  "CROSS TIMBERS ENERGY",
  "CROWN CENTRAL PETROLEUM",
  "CROWNQUEST OPERATING",
  "DALLAS PRODUCTION",
  "DAVIS BROTHERS",
  "DAYLIGHT PETROLEUM",
  "DE3 OPERATING",
  "DECLEVA PAUL",
  "DELRAY OIL",
  "DELTA OIL AND GAS",
  "DENBURY ONSHORE",
  "DEVON ENERGY PRODUCTION COMPANY",
  "DEWBRE PETROLEUM",
  "DIAMOND CHEMICALS COMPANY",
  "DIAMOND S ENERGY COMPANY",
  "DIAMONDBACK ENERGY",
  "DISCOVERY NATURAL RESOURCES",
  "DISCOVERY OPERATING",
  "DJH OIL AND GAS",
  "DOMINION OKLAHOMA TEXAS E AND P",
  "DP PERMIAN OPERATOR LLC",
  "DREYFUS LOUIS NATURAL GAS",
  "DYERSDALE ENERGY",
  "EAGLE FORD OIL",
  "EAGLE OIL AND GAS COMPANY",
  "EAGLERIDGE OPERATING",
  "EASTLAND OPERATING",
  "EASTWEST ENERGY",
  "ECHO PRODUCTION",
  "EL DORADO GAS AND OIL",
  "EL DORADO OIL AND GAS",
  "ENCANA OIL AND GAS",
  "ENDEAVOR ENERGY RESOURCES",
  "ENDURO OIL COMPANY",
  "ENERGAS COMPANY",
  "ENERGEN RESOURCES",
  "ENERGY 2000",
  "ENERVEST OPERATING",
  "ENHANCED ENERGY PARTNERS",
  "ENRE",
  "ENRICH OIL",
  "ENRON OIL AND GAS COMPANY",
  "ENSERCH EXPLORATION",
  "ENSIGN OPERATING COMPANY",
  "ENTERPRISE PRODUCTS OPERATINGLLC",
  "EOG RESOURCES",
  "EP ENERGY E AND P COMPANY",
  "EPIC PERMIAN OPERATING",
  "ERNEST OPERATING COMPANY",
  "EVEREST EXPLORATION COMPANY",
  "EXCO OPERATING COMPANY",
  "EXTEX OPERATING COMPANY",
  "EXXCEL PRODUCTION COMPANY",
  "EXXON MOBIL",
  "FASKEN OIL AND RANCH",
  "FAULCONER VERNON E",
  "FDL OPERATING",
  "FELDERHOFF PRODUCTION COMPANY",
  "FELIX ENERGY HOLDINGS II",
  "FINA OIL AND CHEMICAL COMPANY",
  "FINLEY RESOURCES",
  "FIREBIRD ENERGY LLC",
  "FLINT OAK ENERGY",
  "FOOTHILLS TEXAS",
  "FOREST OIL",
  "FOUNDATION ENERGY MANAGEMENT",
  "FOUR CORNERS PETROLEUM II",
  "FOURPOINT ENERGY",
  "FROSTWOOD ENERGY",
  "G AND F OIL",
  "GAITHER PETROLEUM",
  "GALVESTON BAY ENERGY",
  "GEOMEG ENERGY OPERATING",
  "GEOSOUTHERN ENERGY",
  "GETTY OIL COMPANY",
  "GINCO OPERATING COMPANY",
  "GOLD FIELDS MINING",
  "GOLDKING PRODUCTION COMPANY",
  "GREAT PLAINS RESOURCES",
  "GREAT WESTERN OPERATING COMPANY",
  "GRIZZLY OP OF DELAWARE, LLC",
  "GUIDANCE OIL DEVELOPERSINC1",
  "GUIDON ENERGY MGMT SERVICES",
  "GULF OIL",
  "GUNN OIL COMPANY",
  "HADLEY OIL COMPANY",
  "HALCON OPERATING",
  "HAMMAN OIL AND REFINING COMPANY",
  "HAWKWOOD ENERGY OPERATING",
  "HEADINGTON ENERGY PARTNERS",
  "HENRY PETROLEUM",
  "HENRY RESOURCES",
  "HEXP OPERATING",
  "HIGHMOUNT EXPLORATION AND PRODUCTION TEXAS",
  "HILCORP ENERGY COMPANY",
  "HNG OIL COMPANY",
  "HOPEWELL OPERATING",
  "HOUSTON OIL AND GAS",
  "HOUTCHENS D D",
  "HUBER J M",
  "HUGHES DAN A COMPANY",
  "HUMBLE OIL AND REFINING COMPANY",
  "HUNT OIL COMPANY",
  "IEC",
  "INDEPENDENCE RESOURCES MGMT",
  "ISKANDIA ENERGY OPERATING",
  "J W RESOURCES",
  "JACOBS C E COMPANY",
  "JAGGED PEAK ENERGY",
  "JAY MANAGEMENT COMPANY",
  "JETTA OPERATING COMPANY",
  "JM COX RESOURCES",
  "JOHNSON AND ERNST OPERATING COMPANY",
  "JONES COMPANY",
  "JONES ENERGY",
  "JUNO OPERATING COMPANY II",
  "JUST OIL AND GAS",
  "KAISERFRANCIS OIL COMPANY",
  "KD ENERGY",
  "KEBO OIL AND GAS",
  "KERR MCGEE OIL AND GAS ONSHORE",
  "KILLAM OIL",
  "KILMARNOCK OIL COMPANY",
  "KINDER MORGAN PRODUCTION",
  "KJ ENERGY",
  "KNIGHT MACK",
  "KODIAK OPERATING",
  "KOVAR OPERATING",
  "KTC OIL ENTERPRISES",
  "LAREDO ENERGY OPERATING",
  "LAREDO PETROLEUM",
  "LARGE OPERATING LLC",
  "LARIO OIL AND GAS COMPANY",
  "LATIGO PETROLEUM",
  "LAYLINE ENERGY I",
  "LCS PRODUCTION COMPANY",
  "LECLAIR OPERATING",
  "LEGACY RESERVES OPERATING",
  "LEGEND NATURAL GAS II",
  "LEWIS PETRO PROPERTIES",
  "LIME ROCK RESOURCES IIIA",
  "LINDER JOHN OPERATING",
  "LINN OPERATING",
  "LONESTAR OPERATING",
  "MAC 5 OPERATING",
  "MAGNOLIA OIL AND GAS OPERATING",
  "MAGNUM PRODUCING",
  "MAMMOTH EXPLORATION",
  "MARATHON OIL COMPANY",
  "MASSIE OIL COMPANY",
  "MATADOR PRODUCTION COMPANY",
  "MAVERICK ENERGY AND DEV",
  "MAVERICK PRODUCTION",
  "MCCLURE OIL COMPANY",
  "MCDAY ENERGY",
  "MCFADDEN OIL",
  "MCGOWAN WORKING PARTNERS",
  "MD AMERICA ENERGY",
  "MECO IV",
  "MEDDERS OIL COMPANY",
  "MERCURY OPERATING",
  "MERIT ENERGY COMPANY",
  "MEWBOURNE OIL COMPANY",
  "MILLENNIUM RESOURCES",
  "MITCHELL ENERGY",
  "MOBIL OIL",
  "MOBIL PRODUCING TX AND NM",
  "MOMENTUM OPERATING",
  "MONROE WELL SERVICE",
  "MUIRFIELD EXPLORATION",
  "MURPHY EXPLORATION AND PRODUCTION COMPANY",
  "MUSTANG EXPLORATION",
  "MYERS JAMES B",
  "NATIONAL LAND RESOURCES",
  "NEUMIN PRODUCTION COMPANY",
  "NEWFIELD EXPLORATION MIDCON",
  "NEWMAN OPERATING COMPANY",
  "NOBLE ENERGY",
  "NORTH AMERICAN ROYALTIES",
  "NORTH CENTRAL OIL",
  "OAKRIDGE OIL AND GAS",
  "OIL INVESTORS",
  "OILEX INTL INVESTMENTS",
  "OILWELL OPERATORS",
  "OLSEN ENERGY",
  "ORLAND OIL AND GAS",
  "ORYAN OIL AND GAS",
  "OXY",
  "PAN AMERICAN PETROLEUM",
  "PANTERA ENERGY COMPANY",
  "PARALLEL PETROLEUM",
  "PARKER AND PARSLEY DEVELOPMENT",
  "PARSLEY ENERGY OPERATIONS",
  "PATTERSON PETROLEUM",
  "PEARL BILL H PRODUCTION",
  "PEBA OIL AND GAS",
  "PENN VIRGINIA OIL AND GAS",
  "PETCO PETROLEUM",
  "PETEX",
  "PETROHAWK OPERATING COMPANY",
  "PETROLEGACY ENERGY II",
  "PETROLEUM CORPORATION OF TEXAS",
  "PETROSAURUS",
  "PGM INTERNATIONAL OPERATINGLLC",
  "PHILLIPS PETROLEUM COMPANY",
  "PIONEER NATURAL RESOURCES",
  "PITCOCK",
  "PITTS ENERGY COMPANY",
  "POANDG OPERATING",
  "POLARIS OPERATING LLC",
  "PONDEROSA TX OPERATING",
  "PRESIDIO PETROLEUM",
  "PRIME OPERATING COMPANY",
  "PRIMEXX OPERATING",
  "PRODUCTION RESOURCES",
  "PROLINE ENERGY RESOURCES",
  "QEP ENERGY COMPANY",
  "QUAIL CREEK OIL",
  "QUATRO OIL AND GAS",
  "QUICKSILVER RESOURCES",
  "R LACY SERVICES",
  "R2Q OPERATING",
  "RADCO OPERATIONS",
  "RANGE PRODUCTION COMPANY",
  "RD OIL COMPANY",
  "RED LINE COMPANY",
  "RELENTLESS PERMIAN OPERATING",
  "REMORA MANAGEMENT",
  "REMORA OPERATING",
  "REMUDA OPERATING COMPANY",
  "RENEAU OIL COMPANY",
  "REPSOL OIL & GAS USA, LLC",
  "RHEACO OIL COMPANY",
  "RIDGE OIL COMPANY",
  "RIFE OIL PROPERTIES",
  "RING ENERGY",
  "RIVIERA OPERATING",
  "RJD MANAGEMENT",
  "ROBERTSON RESOURCES",
  "ROCKCLIFF ENERGY OPERATING",
  "ROCKER A OPERATING COMPANY",
  "ROGERS DRILLING COMPANY",
  "ROGERS S K OIL",
  "ROMAC OIL COMPANY",
  "ROSETTA RESOURCES OPERATING",
  "ROVER PETROLEUM OPERATING",
  "RSP PERMIAN",
  "S AND J OPERATING COMPANY",
  "SABINAL ENERGY OPERATING",
  "SABINE OIL AND GAS",
  "SABINE PRODUCTION COMPANY",
  "SABLE PERMIAN RESOURCES LANDLLC",
  "SAGE ENERGY COMPANY",
  "SAGE NATURAL RESOURCES",
  "SAMEDAN OIL",
  "SAMSON LONE STAR",
  "SANCHEZ ENERGY",
  "SANDRIDGE EXPLORATION AND PRODUCTION",
  "SARATOGA PRODUCTION COMPANY",
  "SB STREET OPERATING",
  "SCANDRILL COMPANY",
  "SCHLACHTER OPERATING",
  "SCOUT ENERGY MANAGEMENT",
  "SEA EAGLE FORD",
  "SEABOARD OPERATING COMPANY",
  "SEAGULL OPERATING",
  "SEM OPERATING COMPANY",
  "SEVEN CROSS OPERATING",
  "SHALLOW PRODUCTION OPER",
  "SHARP IMAGE ENERGY",
  "SHELL OIL COMPANY",
  "SHERIDAN PRODUCTION CO III, LLC",
  "SHERIDAN PRODUCTION COMPANY",
  "SILVER CREEK OIL AND GAS",
  "SILVERBOW RESOURCES OPER",
  "SLANT OPERATING",
  "SM ENERGY COMPANY",
  "SMITH PIPE OF ABILENE",
  "SMITH PRODUCTION",
  "SOJOURNER DRILLING",
  "SONAT EXPLORATION COMPANY",
  "SOUTH SAM OPERATING COMPANY",
  "SOUTHEASTERN RESOURCES",
  "SOUTHWEST GAS SYSTEMS",
  "SOUTHWEST ROYALTIES",
  "STAMPER OPERATING",
  "STANOLIND PRODUCTION",
  "STASNEY WELL SERVICE",
  "STEPHENS AND JOHNSON OPERATING COMPANY",
  "STOUT ENERGY",
  "STOVALL OPERATING COMPANY",
  "STRAT LAND EXPLORATION COMPANY",
  "STRONGHOLD ENERGY II OPER",
  "SUEANN OPERATING LC",
  "SULLIVAN HOLLIS R",
  "SULPHUR RIVER EXPLORATION",
  "SUMMIT PETROLEUM",
  "SUN EXPLORATIONPRODUCTION COMPANY",
  "SUNDOWN ENERGY",
  "SUNOCO ENERGY DEVELOPMENT COMPANY",
  "SURGE OPERATING",
  "SWANNER PROPERTIES",
  "TABULA RASA ENERGY",
  "TALISMAN ENERGY",
  "TAMARACK PETROLEUM COMPANY",
  "TANDEM ENERGY",
  "TANOS EXPLORATION II",
  "TC OIL COMPANY",
  "TEMPLAR OPERATING LLC",
  "TENNECO OIL COMPANY",
  "TENNECO URANIUM",
  "TEP BARNETT",
  "TERRA RESOURCES",
  "TEXACO",
  "TEXACO E AND P",
  "TEXAS AMERICAN RESOURCES COMPANY",
  "TEXAS ENERGY OPERATIONS LC",
  "TEXAS OIL AND GAS",
  "TEXAS PACIFIC OIL COMPANY",
  "TEXAS PETROLEUM INVESTMENT COMPANY",
  "TEXAS SECONDARY OIL",
  "TEXASGULF",
  "TEXLAND PETROLEUM",
  "TEXLANDRECTOR AND SCHUMACHER",
  "TEXXOL OPERATING COMPANY",
  "THE ANACONDA",
  "THE LONG TRUSTS",
  "THE SUPERIOR OIL COMPANY",
  "THOMPSON J CLEO",
  "THOMPSON JOHN R OPERATING",
  "THREE P OPERATING COGP",
  "THREE R OIL COMPANY",
  "THRONE PETROLEUM RESOURCES",
  "TORRENT OIL",
  "TREK RESOURCES",
  "TRIC RESOURCES",
  "TRINITY OPERATING USG",
  "TRIVISTA OPERATING",
  "TRIVIUM OPERATING",
  "TXO MINERALS",
  "TXO PRODUCTION",
  "U S ENERGY DEVELOPMENT",
  "U S OPERATING",
  "UNIDENTIFIED",
  "UNION OIL COMPANY OF CALIFORNIA",
  "UNION PACIFIC RESOURCES COMPANY",
  "UNION TEXAS PETROLEUM",
  "UNIT PETROLEUM COMPANY",
  "UNITEX OIL AND GAS",
  "UNKNOWN",
  "UPHAM OIL AND GAS COMPANY",
  "UPP OPERATING LLC",
  "URBAN OIL AND GAS GROUP",
  "V AND H OIL",
  "VALENCE OPERATING COMPANY",
  "VAN OPERATING",
  "VANCO OIL AND GAS",
  "VANGUARD OPERATING",
  "VANTAGE FORT WORTH ENERGY",
  "VENADO OPERATING COMPANY",
  "VERADO ENERGY",
  "VERDUN OIL AND GAS",
  "VESS OIL",
  "VICEROY PETROLEUM",
  "VINLAND TEXAS SERVICES LLC",
  "VIRTEX OPERATING COMPANY",
  "WAGNER OIL COMPANY",
  "WALSH AND WATTS",
  "WALSH PETROLEUM",
  "WEATHERLY OIL AND GAS",
  "WELDER EXPLORATION AND PRODUCTION",
  "WESMOR DRILLING",
  "WESTERN ENERGY GROUP",
  "WFW PRODUCTION COMPANY",
  "WHITE KNIGHT PRODUCTION",
  "WHITE OAK OPERATING COMPANY",
  "WHITE ROCK OIL AND GAS",
  "WHITING OIL AND GAS",
  "WILLOWBEND INVESTMENTS",
  "WINCHESTER OIL COMPANY",
  "WISCHKAEMPER KENNETH",
  "WO OPERATING COMPANY",
  "WOODBINE PRODUCTION",
  "WPX ENERGY",
  "WT WAGGONER ESTATE",
  "WTG EXPLORATION",
  "XOG OPERATING",
  "XTO ENERGY",
  "YOUNG MARSHALL R OIL COMPANY",
];

export default function OperatorFilterJ() {
  const [stateNav, setStateNav] = useContext(NavigationContext);
  const [operatorName, setOperatorName] = React.useState(
    stateNav.operatorName ? stateNav.operatorName : []
  );
  const handleOperatorChange = (value) => {
    let filter;
    if (value && value.length) {
      filter = ["match", ["get", "operator"], value, true, false];
      setStateNav((stateNav) => ({ ...stateNav, operatorName: value }));
      setOperatorName(value);
    } else {
      filter = null;
      setStateNav((stateNav) => ({ ...stateNav, operatorName: [] }));
    }
    setStateNav((stateNav) => ({ ...stateNav, filterOperator: filter }));
  };

  return (
    <Autocomplete
      defaultValue={stateNav.operatorName ? stateNav.operatorName : []}
      onChange={(event, newValue) => {
        handleOperatorChange(newValue);
      }}
      multiple
      options={operatorList}
      renderInput={(params) => (
        <TextField
          {...params}
          variant="outlined"
          label="Operator"
          placeholder=""
          fullWidth
        />
      )}
      disableListWrap
      id="virtualize-operators"
      //style={{ maxWidth: 300, minWidth: 120 }}
    />
  );
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// import React, { useContext, useEffect, useState } from "react";
// import TextField from "@material-ui/core/TextField";
// import Autocomplete from "@material-ui/lab/Autocomplete";
// import { NavigationContext } from "../NavigationContext";
// import { OPERATORSQUERY } from "../../../graphQL/useQueryOperators";
// import { useLazyQuery } from "@apollo/react-hooks";
// import CircularProgress from "@material-ui/core/CircularProgress";

// export default function OperatorFilterJ() {
//   const [stateNav, setStateNav] = useContext(NavigationContext);
//   // const [operatorName, setOperatorName] = React.useState(
//   //   stateNav.operatorName ? stateNav.operatorName : null
//   // );
//   const [operatorsList, setOperatorsList] = useState([]);
//   const [operatorName, setOperatorName] = useState();

//   const [getOperatorsList, { data, loading }] = useLazyQuery(OPERATORSQUERY);

//   // useEffect(() => {
//   //   getOperatorsList();
//   // }, []);

//   useEffect(() => {
//     console.log("datttttttttttttt", data);
//     if (data) {
//       setOperatorsList(data.operators);
//     }
//   }, [data]);

//   // useEffect(() => {
//   //   console.log("navvvvvvv",stateNav.operators)
//   //   if (!stateNav.operators) {
//   //     getOperatorsList();
//   //   } else {
//   //     setOperatorsList(stateNav.operators);
//   //   }
//   // }, [stateNav.operators]);

//   // useEffect(() => {
//   //   console.log("datttttttttttttt",data)

//   //   if (data) {
//   //     setStateNav((state) => ({ ...state, operators: data.operators }));
//   //   }
//   // }, [data]);

//   const handleOperatorChange = (value) => {
//     console.log("///////////////");
//     if (value.trim().length > 1) {
//       getOperatorsList({
//         variables: {
//           search: value.trim(),
//         },
//       });
//     }

//     // let filter;
//     // if (value && value.length) {
//     //   filter = ["match", ["get", "operator"], value, true, false];
//     //   setStateNav((stateNav) => ({ ...stateNav, operatorName: value }));
//     //   // setOperatorName(value);
//     // } else {
//     //   filter = null;
//     //   setStateNav((stateNav) => ({ ...stateNav, operatorName: null }));
//     // }
//     // setStateNav((stateNav) => ({ ...stateNav, filterOperator: filter }));
//   };

//   return loading ? (
//     <CircularProgress color="secondary" size={28} />
//   ) : (
//     <Autocomplete
//       defaultValue={operatorName}
//       onChange={(event, newValue) => {
//         handleOperatorChange(newValue);
//       }}
//       multiple
//       options={operatorsList}
//       renderInput={(params) => (
//         <TextField
//           {...params}
//           variant="outlined"
//           label="Operator"
//           placeholder=""
//           fullWidth
//         />
//       )}
//       disableListWrap
//       id="virtualize-operators"
//       //style={{ maxWidth: 300, minWidth: 120 }}
//     />
//   );
// }
