import React, { useState, createContext } from "react";

const NavigationContext = createContext([{}, () => {}]);

const NavigationContextProvider = (props) => {
  const [stateNav, setStateNav] = useState({
    selectedMenuIndexFind: 0,
    selectedMenuIndexTrack: 0,
    selectedMenuIndexTransact: 0,
    selectedMenuIndexTitle: 0,
    selectedMenuIndexAlerts: 0,
    selectedMenuIndexDashboard: 0,
    selectedMenuIndexContacts: 0,
    selectedMenuIndexStudio: 0,
    totalFilterCount: 0,
    filterWellProfile: null,
    filterWellType: null,
    filterWellStatus: null,
    filterOperator: null,
    filterInterest: null,
    filterBasin: null,
    filterAOI: null,
    filterParcel: null,
    filterPlay: null,
    filterOwnerType: null,
    filterCumulativeOil: null,
    filterCumulativeGas: null,
    filterCumulativeWater: null,
    filterFirstMonthWater: null,
    filterFirstThreeMonthWater: null,
    filterFirstSixMonthWater: null,
    filterFirstTwelveMonthWater: null,
    filterLastMonthWater: null,
    filterLastSixMonthWater: null,
    filterLastTwelveMonthWater: null,
    filterFirstMonthGas: null,
    filterFirstThreeMonthGas: null,
    filterFirstSixMonthGas: null,
    filterFirstTwelveMonthGas: null,
    filterLastMonthGas: null,
    filterLastSixMonthGas: null,
    filterLastTwelveMonthGas: null,
    filterFirstMonthOil: null,
    filterFirstSixMonthOil: null,
    filterFirstTwelveMonthOil: null,
    filterLastMonthOil: null,
    filterLastSixMonthOil: null,
    filterLastTwelveMonthOil: null,
    filterNoOwnerCount: null,
    filterOwnerConfidence: null,
    filterHasOwners: null,
    filterTags: null,
    filterAllInterestTypes: null,
    filterAllOwnershipTypes: null,
    filterGeography: null,
    filterGeographyState: null,
    filterGeographyCounty: null,
    filterGeographySurvey: null,
    filterGeographyAbstract: null,
    filterOwnerWellInterestSum: null,
    filterOwnerCount: null,
    filterDrawing: [],
    filterTrackedWells: false,
    filterTrackedOwners: false,
    searchInputValue: null,
    statusName: [],
    typeName: [],
    profileName: [],
    ownerCountWell: [],
    appraisalWell: [],
    interestName: [],
    defaultOn: null,
    m1neralDefaultFilters: null,
    basinName: [],
    aoiName: [],
    parcelName: [],
    playName: [],
    prodOptions: [],
    ownerTypeName: [],
    dateTypeName: [],
    countyName: null,
    stateName: null,
    displayStateName: null,
    GrId1: null,
    GrId2: null,
    GrId3: null,
    GrId4: null,
    GrId5: null,
    surveyName: null, ////
    abstractName: null, ////
    operatorName: [],
    wellFilterCount: 0,
    ownershipFilterCount: 0,
    productionFilterCount: 0,
    geographyFilterCount: 0,
    valuationFilterCount: 0,
    aiFilterCount: 0,
    operators: null,
    filterPermitDateRange: null,
    filterSpudDateRange: null,
    filterCompletetionDateRange: null,
    filterFirstProdDateRange: null,
    permitDateFrom: null,
    permitDateTo: null,
    spudDateFrom: null,
    spudDateTo: null,
    completetionDateFrom: null,
    completetionDateTo: null,
    firstProdDateFrom: null,
    firstProdDateTo: null,
    displayFilters: null,
    statesInFilter: null,
    countiesInFilter: null,
    surveysInFilter: null,
    asbtractsInFilter: null,
    trackTabsValue: 0,
    currentUserFilters: null,
    filterHasOwnerCount: null,
    m1neralDefaultsOnOff: true,
    m1neralCehckOnOff: true,
    filterWellAppraisal: null,
    filterOwnerAppraisals: null,
    ownerWellInterestSum: null,
    drawingMode: null,
    filterFeatureId: null,
    isProfileOpen: true,
    selectedTags: [],
    wellsIdsFromTags: [],
  });
  return (
    <NavigationContext.Provider value={[stateNav, setStateNav]}>
      {props.children}
    </NavigationContext.Provider>
  );
};

export { NavigationContext, NavigationContextProvider };
